Repository Hypixel-API-Reborn/hypixel-api-reborn, pull requests merged in 2024-08, with the labels that each got.

#587 Fix bestiary constants
  src/utils/Constants.js
Labels: size/L

#590 Feat/dungeons completions
  src/structures/SkyBlock/SkyblockMember.js
  src/utils/SkyblockUtils.js
  typings/index.d.ts
Labels: size/M

#589 Feat/kuudra
  src/structures/SkyBlock/SkyblockMember.js
  src/utils/SkyblockUtils.js
  typings/index.d.ts
Labels: size/M

#591 add garden to SkyblockProfile
  src/structures/SkyBlock/SkyblockProfile.js
  typings/index.d.ts
Labels: size/XS

#595 Update index.d.ts
  typings/index.d.ts
Labels: size/XS

#596 Fix spelling
  src/structures/SkyBlock/SkyblockGarden.js
  typings/index.d.ts
Labels: size/S

#597 Fix/crimson
  src/structures/SkyBlock/SkyblockMember.js
  src/utils/SkyblockUtils.js
  typings/index.d.ts
Labels: size/M

#600 fix getSkyblockGarden throwing error when user has no garden data
  src/API/skyblock/getGarden.js
  src/structures/SkyBlock/SkyblockGarden.js
Labels: size/M

#601 Fixed Typing for <SkyblockMember>.dungeons.essence
  typings/index.d.ts
Labels: size/S

#610 fix: gexp totalHistory summing in the wrong order
  src/utils/Guild.js
Labels: size/XS
